sudo: required
services:
- docker

env:
  matrix:
  - SUITE=artful
  - SUITE=buster
  - SUITE=sid
  - SUITE=stretch
  - SUITE=xenial
  - SUITE=zesty

branches:
  only: master

script:
- docker build -t ${TRAVIS_REPO_SLUG%/*}/anbox-devel:$SUITE $SUITE

after_success:
- docker images
